name : "dance power 2014"
description : ""

url : "http://dancepower.org"

paginate : 10


markdown : redcarpet

permalink : /:categories/:year/:month/:day/:title

pygments : true

blog_structure : "/blog/"